[package]
name = "rurity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
winit = "0.27.2"
engine = { package = "rurity_engine", path = "../engine/" }

[features]
no_log = ["engine/no_log"]
log = ["engine/log"]
