name: rust-check analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '32 5 * * 6'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
      - name: test
        run: cargo test --verbose
      - name: rustfmt
        run: cargo fmt -- --check
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
      - name: test
        run: cargo test --verbose
      - name: rustfmt
        run: cargo fmt -- --check
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
      - name: test
        run: cargo test --verbose
      - name: rustfmt
        run: cargo fmt -- --check
