name: rust-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
        continue-on-error: true
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true
      - name: test
        run: cargo test --verbose
        continue-on-error: true
      - name: rustfmt
        run: cargo fmt -- --check
        continue-on-error: true
      - name: miri
        run: |
            rustup toolchain install nightly --component miri
            rustup override set nightly
            cargo miri setup
            cargo miri test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
        continue-on-error: true
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true
      - name: test
        run: cargo test --verbose
        continue-on-error: true
      - name: rustfmt
        run: cargo fmt -- --check
        continue-on-error: true
      - name: miri
        run: |
            rustup toolchain install nightly --component miri
            rustup override set nightly
            cargo miri setup
            cargo miri test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        run: cargo check --all-targets --all-features --verbose
        continue-on-error: true
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true
      - name: test
        run: cargo test --verbose
        continue-on-error: true
      - name: rustfmt
        run: cargo fmt -- --check
        continue-on-error: true
      - name: miri
        run: |
            rustup toolchain install nightly --component miri
            rustup override set nightly
            cargo miri setup
            cargo miri test
